// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VideoApp.Data;

namespace VideoApp.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20210622082414_InitCreateDB")]
    partial class InitCreateDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ActorVideo", b =>
                {
                    b.Property<int>("ActorsActorId")
                        .HasColumnType("int");

                    b.Property<int>("VideosVideoId")
                        .HasColumnType("int");

                    b.HasKey("ActorsActorId", "VideosVideoId");

                    b.HasIndex("VideosVideoId");

                    b.ToTable("ActorVideo");
                });

            modelBuilder.Entity("VideoApp.Models.Actor", b =>
                {
                    b.Property<int>("ActorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DayOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ActorId");

                    b.ToTable("Actors");

                    b.HasData(
                        new
                        {
                            ActorId = 1,
                            DayOfBirth = new DateTime(1955, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Bruce",
                            LastName = "Willis"
                        },
                        new
                        {
                            ActorId = 2,
                            DayOfBirth = new DateTime(1963, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Johny",
                            LastName = "Depp"
                        },
                        new
                        {
                            ActorId = 3,
                            DayOfBirth = new DateTime(1957, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Bernie",
                            LastName = "Mac"
                        },
                        new
                        {
                            ActorId = 4,
                            DayOfBirth = new DateTime(1979, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Kevin",
                            LastName = "Hart"
                        });
                });

            modelBuilder.Entity("VideoApp.Models.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenreId");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            GenreId = 1,
                            Name = "Action"
                        },
                        new
                        {
                            GenreId = 2,
                            Name = "Comedy"
                        },
                        new
                        {
                            GenreId = 3,
                            Name = "Sci-Fi"
                        },
                        new
                        {
                            GenreId = 4,
                            Name = "Horror"
                        });
                });

            modelBuilder.Entity("VideoApp.Models.Video", b =>
                {
                    b.Property<int>("VideoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VideoId");

                    b.HasIndex("GenreId");

                    b.ToTable("Videos");

                    b.HasData(
                        new
                        {
                            VideoId = 1,
                            GenreId = 2,
                            Name = "Ride Along"
                        },
                        new
                        {
                            VideoId = 2,
                            GenreId = 1,
                            Name = "Oceans 11"
                        },
                        new
                        {
                            VideoId = 3,
                            GenreId = 4,
                            Name = "The Sixth Sense"
                        },
                        new
                        {
                            VideoId = 4,
                            GenreId = 3,
                            Name = "Transcendence"
                        });
                });

            modelBuilder.Entity("ActorVideo", b =>
                {
                    b.HasOne("VideoApp.Models.Actor", null)
                        .WithMany()
                        .HasForeignKey("ActorsActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoApp.Models.Video", null)
                        .WithMany()
                        .HasForeignKey("VideosVideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VideoApp.Models.Video", b =>
                {
                    b.HasOne("VideoApp.Models.Genre", "Genres")
                        .WithMany("Videos")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genres");
                });

            modelBuilder.Entity("VideoApp.Models.Genre", b =>
                {
                    b.Navigation("Videos");
                });
#pragma warning restore 612, 618
        }
    }
}
